<?php

namespace EasySwoole\HttpAnnotation\Tests\TestController;


use EasySwoole\HttpAnnotation\AnnotationController;
use EasySwoole\HttpAnnotation\AnnotationTag\ApiAuth;
use EasySwoole\HttpAnnotation\AnnotationTag\ApiGroupAuth;

/**
 * Class Param
 * @package EasySwoole\HttpAnnotation\Tests\TestController
 * @ApiGroupAuth(name="groupAuth",required="",notEmpty="")
 * @\EasySwoole\HttpAnnotation\AnnotationTag\Param(name="groupParam",required="",notEmpty="")
 */
class Param extends AnnotationController
{
    /**
     * @ApiAuth(name="onRequestAuth",required="",notEmpty="")
     * @\EasySwoole\HttpAnnotation\AnnotationTag\Param(name="onRequestParam",required="",notEmpty="")
     */
    public function onRequest(?string $action): ?bool
    {
        return parent::onRequest($action); // TODO: Change the autogenerated stub
    }

    /**
     * @ApiAuth(name="auth",required="",notEmpty="")
     * @\EasySwoole\HttpAnnotation\AnnotationTag\Param(name="param",required="",notEmpty="")
     */
    public function index()
    {
        $this->response()->write(json_encode($this->request()->getQueryParams()));
    }
}